/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/s9d8oNkx36o
 */
import Link from "next/link";
import {
  CardTitle,
  CardHeader,
  CardContent,
  CardFooter,
  Card,
} from "@/components/ui/card";
import { Avatar } from "./Avatar";
import { AvatarImage } from "@radix-ui/react-avatar";
import Spotify from "./Spotify";

export function MainPage() {
  return (
    <div key="1" className="bg-white text-gray-800 rounded lg:w-4/5">
      <header className="flex justify-between items-center py-6 px-10 border-b">
        <div className="space-x-4 hidden sm:hidden md:flex lg:flex">
          <Link href={"https://github.com/Xwaffle1/"}>
            <div className="text-yellow-600 hover:bg-gray-200 rounded cursor-pointer p-1">
                <GithubIcon className="text-yellow-600" />
            </div>
          </Link>
          <Link href={"https://www.linkedin.com/in/chase-myers-56a394152/"}>
            <div className="text-yellow-600 hover:bg-gray-200 rounded cursor-pointer p-1">
              <LinkedinIcon className="text-yellow-600" />
            </div>
          </Link>
          <Link href={"mailto:me@chasem.dev"}>
            <div className="text-yellow-600 hover:bg-gray-200 rounded cursor-pointer p-1">
              <MailIcon className="text-yellow-600" />
            </div>
          </Link>
        </div>
        <nav className="flex space-x-6  hidden sm:hidden md:flex lg:flex">
          <div className="text-gray-800 hover:bg-gray-200 hover:text-yellow-600 rounded cursor-pointer p-1">
            <Link href="#work">Work Experience</Link>
          </div>
          <div className="text-gray-800 hover:bg-gray-200 hover:text-yellow-600 rounded cursor-pointer p-1">
            <Link href="#projects">Projects</Link>
          </div>
          <div className="text-white bg-yellow-600 hover:bg-yellow-200 hover:text-gray-800 rounded cursor-pointer p-1 px-2">
            <Link href="/Chase-Myers-Resume-11-27.pdf">View Resume</Link>
          </div>
        </nav>
      </header>
      <main className="py-10 px-5 sm:px-5 md:px-10 lg:px-10">
        <section className="text-center">
          <img
            className="relative flex shrink-0 overflow-hidden w-64 h-64 rounded-full mx-auto border-yellow-600 border-4"
            src="me.jpg"
          ></img>
          <h1 className="text-4xl font-bold mt-4">Hi! I{"'"}m Chase</h1>
          <div className="flex justify-center">
            <p className="text-gray-600 mt-2 text-left w-3/4">
              An outgoing and experienced Software Engineer who thrives in
              ambiguity, with hard work effort, great companionship, and is
              eager to hear about your opportunities.
            </p>
          </div>
        </section>
        <div className="flex sm:flex md:hidden lg:hidden justify-center my-8">
          <div className="text-center text-white bg-yellow-600 hover:bg-yellow-200 hover:text-gray-800 rounded cursor-pointer p-2 w-1/2">
              <Link href="/Chase-Myers-Resume-11-27.pdf">View Resume</Link>
          </div>
        </div>
        <section className="mt-10">
          <h2 className="text-2xl font-bold text-gray-800 mb-4">Education</h2>
          <div className="bg-gray-100 p-6 rounded-lg">
            <GraduationCapIcon className="text-yellow-600" />
            <h3 className="text-lg font-semibold mt-2">Bachelors of Science</h3>
            <p className="text-gray-600">
              Computer Science, Western Michigan University
            </p>
            <p className="text-gray-600">December 2019</p>
          </div>
        </section>
        <section className="mt-10" id="work">
          <h2 className="text-2xl font-bold text-gray-800 mb-4">
            Work Experience
          </h2>
          <div className="bg-blue-100 p-6 rounded-lg mb-6">
            <BriefcaseIcon className="text-yellow-600" />
            <h3 className="text-lg font-semibold mt-2">
              Software Engineer - Indeed Recruiter Extension
            </h3>
            <p className="text-gray-600">Indeed.com</p>
            <p className="text-gray-600">Aug 2022 - Present</p>
            <ul className="list-disc pl-6 mt-2 text-gray-600">
              <li>
                Directed a squad of three engineers in collaboration with a
                Product Manager and UX Designer to develop designated features
                each quarter.
              </li>
              <li>
                Successfully deprecated third party authentication and
                transitioned to Indeed{"'"}s first-party cookie authentication
                in React.
              </li>
              <li>
                Delivered complex solutions requiring modifications across
                multiple code repositories, including React, AngularJS, Rails,
                and Java SpringBoot, demonstrating versatility in software
                development.
              </li>
              <li>
                Coordinated the design and release of features spanning multiple
                cross functional teams
              </li>
              <li>
                Integrated existing Indeed features such as Hiring Insights,
                Analytics, and Resume Outreach, expanding the extension{"'"}s
                functionality and user engagement.
              </li>
              <li>
                Facilitated the refinement of ambiguous feature proposals and
                implement technical adaptations meeting requirements provided by
                Product
              </li>
            </ul>
          </div>
          <div className="bg-gray-100 p-6 rounded-lg mb-6">
            <BriefcaseIcon className="text-yellow-600" />
            <h3 className="text-lg font-semibold mt-2">Software Engineer II</h3>
            <p className="text-gray-600">Level Data Inc.</p>
            <p className="text-gray-600">Apr 2021 - Aug 2022</p>
            <ul className="list-disc pl-6 mt-2 text-gray-600">
              <li>
                Pioneered a data validation platform for K-12 school districts
                to assist with keeping their data clean for state reporting.
              </li>
              <li>
                Containerized webpack bundle, NodeJS API, and batch processing
                jobs using Docker, and JFrog artifactory.
              </li>
              <li>
                Researched, configured, and deployed Keycloak authentication to
                Kubernetes.
              </li>
              <li>
                Incorporated multi-tenant authentication and authorization using
                Keycloak and Express routes on within NodeJS.
              </li>
              <li>
                Built Role Base Access Control within the platform, allowing
                district admins to delegate permissions as needed.
              </li>
              <li>
                Configured and setup automated deployments {"("}CI/CD{")"} using
                SnakeCI and automatic publishing of new versions.
              </li>
            </ul>
            <h3 className="text-lg font-semibold mt-2">
              Software Integration Engineer
            </h3>
            <p className="text-gray-600">Level Data Inc.</p>
            <p className="text-gray-600">Dec 2018 - Apr 2021</p>
            <ul className="list-disc pl-6 mt-2 text-gray-600">
              <li>
                Maintained library with thousands of scheduled jobs depending on
                it.
              </li>
              <li>
                Assisted data integration for school districts around the world
                with {"‘"}connectors{"’"} {"("}E.T.L{")"}
              </li>
              <li>
                Worked closely with school representatives and maintained
                project deadlines.
              </li>
              <li>
                Designed and implemented an error monitoring web portal using
                SpringBoot to save workers 100+ hours.
              </li>
              <li>
                Created new integrations to obtain data from a variety of
                different source locations including using Rest APIs, executable
                files, and web scraping.
              </li>
            </ul>
          </div>
          <div className="bg-gray-100 p-6 rounded-lg mb-6">
            <BriefcaseIcon className="text-yellow-600" />
            <h3 className="text-lg font-semibold mt-2">Software Developer</h3>
            <p className="text-gray-600">Journey Gaming</p>
            <p className="text-gray-600">Feb 2016 - Dec 2018</p>

            <ul className="list-disc pl-6 mt-2 text-gray-600">
              <li>
                Constructed a virtual trading market for users to buy and sell
                items, leveraging Java and MySQL, for user-to-user item
                transactions
              </li>
              <li>
                Provided technical support for a gaming network of over 100
                active users, ensuring smooth and uninterrupted gameplay
                experiences
              </li>
              <li>
                Actively integrated new features into the codebase, addressing
                feedback and requests from both users and staff, enhancing user
                engagement and platform functionality.
              </li>
            </ul>
          </div>
          <div className="bg-gray-100 p-6 rounded-lg mb-6">
            <BriefcaseIcon className="text-yellow-600" />
            <h3 className="text-lg font-semibold mt-2">Contracted Software Engineer</h3>
            <p className="text-gray-600">Self Employed</p>
            <p className="text-gray-600">2014 - 2018</p>

            <ul className="list-disc pl-6 mt-2 text-gray-600">
              <li>
                Dungeon Realms
                  <ul className="dashed list-inside">
                    <li>
                      Conducted a comprehensive refactoring and rewriting of the existing codebase in
                Java, focusing on maintainability and efficiency.
                    </li>
                    <li>
                      Used MongoDB and SQL to seek an effective database system for the network{"'"}s large influx of queries.
                    </li>
                  </ul>
              </li>
              <li>
                Counter Craft
                  <ul className="dashed list-inside">
                    <li>
                    Facilitated a large amount of Cloud, Server and Client interaction using Netty.
                    </li>
                    <li>
                    Acquired a large grasp of OpenGL using the Java library
                    </li>
                  </ul>
              </li>
              <li>
                Poke Trials
                  <ul className="dashed list-inside">
                    <li>
                    Developed a Minecraft server game, inspired by Pokemon Go, utilizing Java to recreate a similar gameplay experience.
                    </li>
                    <li>
                    Synchronized users virtual inventory between cross network decentralized servers.
                    </li>
                    <li>
                    Worked closely with YouTube content creators, providing technical support and maintaining effective communication channels.
                    </li>
                  </ul>
              </li>
            </ul>
          </div>
        </section>
        <h2 className="text-2xl font-bold text-gray-800 mb-4">Projects</h2>
        <section className="mt-10 flex flex-row justify-center w-full" id="projects">
          <div className="w-full">
            <div className="grid justify-center sm:grid-cols-1 lg:grid-cols-2 md:grid-cols-1 gap-4">
            <Card className="min">
                <CardHeader>
                  <CardTitle className="p-0">Tunnels.gg</CardTitle>
                </CardHeader>
                <CardContent>
                  <img
                    alt="Tunnels.gg"
                    className="w-full h-64 sm:h-64 md:h-96 lg:h-96 object-cover rounded"
                    height="200"
                    src="/tunnels.png"
                    style={{
                      aspectRatio: "200/200",
                      objectFit: "cover",
                    }}
                    width="200"
                  />
                  <div className="mt-2 flex w-full">
                    <p className="text-gray-400 w-full">
                    A Discord bot that enables a single Discord server to create a private or public connection. By sharing its unique code, other servers can easily link their own channels to a Tunnel.
                    </p>
                  </div>
                </CardContent>
                <CardFooter>
                  <Link className="text-yellow-600 hover:underline hover:bg-gray-200 rounded p-1" href="https://tunnels.gg?ref=chasem.dev">
                    Visit Site
                  </Link>
                </CardFooter>
              </Card>
              <Card>
                <CardHeader>
                  <CardTitle className="p-0">Inventories.gg</CardTitle>
                </CardHeader>
                <CardContent>
                  <img
                    alt="Project 1"
                    className="w-full h-64 sm:h-64 md:h-96 lg:h-96 border-2 border-gray-200 rounded"
                    height="200"
                    src="/inventories.png"
                    style={{
                      aspectRatio: "200/200",
                      objectPosition: 'top',
                      objectFit: 'scale-down'
                    }}
                    width="200"
                  />
                  <div className="mt-2 flex w-full">
                    <p className="text-gray-400 w-full">
                      A Minecraft inventory viewer for any server who wants to
                      display their players inventories for others to see.
                      Technlogies include Material-UI, MongoDB, React and
                      NextJS. Authentication is using OAuth handled by Clerk.dev
                    </p>
                  </div>
                </CardContent>
                <CardFooter>
                  <Link className="text-yellow-600 hover:underline hover:bg-gray-200 rounded p-1" href="https://inventories.chasem.dev?ref=chasem.dev">
                    Visit Site
                  </Link>
                </CardFooter>
              </Card>
              <Card className="w-full">
                <CardHeader>
                  <CardTitle>Godot Kart</CardTitle>
                </CardHeader>
                <CardContent>
                  <img
                    alt="Project 2"
                    className="w-full h-64 sm:h-64 md:h-96 lg:h-96 object-cover rounded"
                    height="200"
                    src="/godot.png"
                    style={{
                      aspectRatio: "200/200",
                      objectFit: "cover",
                    }}
                    width="200"
                  />
                  <div className="mt-2 flex w-full">
                    <p className="text-gray-400 w-full">
                    A Mario Kart inspired multiplayer Kart racing game built using the Godot Engine. After discovering someone made a single player demo of the game, I took lead on building the multiplayer behind the game which includes all client interpolation, a master game server browser, and the game servers.
                    </p>
                  </div>
                </CardContent>
                <CardFooter>
                  <Link className="text-yellow-600 hover:underline hover:bg-gray-200 rounded p-1" href="https://www.youtube.com/watch?v=5Zc2x79yEBA">
                    Visit Site
                  </Link>
                </CardFooter>
              </Card>
              <Card>
                <CardHeader>
                  <CardTitle>Hashmap.me</CardTitle>
                </CardHeader>
                <CardContent>
                  <img
                    alt="Project 3"
                    className="w-full h-64 sm:h-64 md:h-96 lg:h-96 rounded border-2 border-gray-200"
                    height="200"
                    src="/hashmap.png"
                    style={{
                      aspectRatio: "200/200",
                      objectFit: 'cover',
                    }}
                    width="200"
                  />
                  <div className="mt-2 flex w-full">
                    <p className="text-gray-400 w-full">
                      Simplifying the ability to persist data for applications. Anytime a developer wants to begin a project they will begin by storing data into their applications memory. This aims to allow developers to simply upload their memory cache through HTTP and then on startup pull that cache back down.
                    </p>
                  </div>
                </CardContent>
                <CardFooter>
                  <Link className="text-yellow-600 hover:underline hover:bg-gray-200 rounded p-1" href="https://hashmap.me?ref=chasem.dev">
                    Visit Site
                  </Link>
                </CardFooter>
              </Card>
              <Card>
                <CardHeader>
                  <CardTitle>International Dog House</CardTitle>
                </CardHeader>
                <CardContent>
                  <img
                    alt="International Dog House"
                    className="w-full h-64 sm:h-64 md:h-96 lg:h-96 border-2 border-gray-200 rounded"
                    height="200"
                    src="/doghouse.png"
                    style={{
                      aspectRatio: "200/200",
                      objectFit: "scale-down",
                    }}
                    width="200"
                  />
                  <p className="text-gray-600 mt-2">
                    Minimalist website created and hosted for a local business in my hometown.
                  </p>
                </CardContent>
                <CardFooter>
                  <Link className="text-yellow-600 hover:underline hover:bg-gray-200 rounded p-1" href="https://international-dog-house.vercel.app/">
                    Visit Site
                  </Link>
                </CardFooter>
              </Card>
            </div>
          </div>
        </section>
      </main>
      <footer className="mt-10 p-6 border-t flex flex-row w-full gap-4">
        <div className="flex w-full">
          <Spotify />
        </div>
        <div className="flex-col hidden sm:hidden md:flex lg:flex justify-center">
          <div className="text-white bg-yellow-600 hover:bg-yellow-200 hover:text-gray-800 rounded cursor-pointer p-1 px-2 flex-nowrap text-nowrap">
              <Link href="/Chase-Myers-Resume-11-27.pdf">View Resume</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}

function FacebookIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z" />
    </svg>
  );
}

function GithubIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4" />
      <path d="M9 18c-4.51 2-5-2-7-2" />
    </svg>
  );
}

function LinkedinIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z" />
      <rect width="4" height="12" x="2" y="9" />
      <circle cx="4" cy="4" r="2" />
    </svg>
  );
}

function MailIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="16" x="2" y="4" rx="2" />
      <path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7" />
    </svg>
  );
}

function GraduationCapIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 10v6M2 10l10-5 10 5-10 5z" />
      <path d="M6 12v5c3 3 9 3 12 0v-5" />
    </svg>
  );
}

function BriefcaseIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="14" x="2" y="7" rx="2" ry="2" />
      <path d="M16 21V5a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16" />
    </svg>
  );
}
